Xcode 10.2 / Swift 4.2 Fixes
danielgindi/ChartsRealm pull request #28
Opened 2019-04-03 18:51 UTC by cdstamper

BUILD FIXES FOR SWIFT 4.2

Toward issue #27 this PR fixes several build issues in Swift 4.2, which may only be present when using later (4.2-compatible) versions of several dependencies.

• IPieChartDataSet dependency requires `useValueColorForLine` in data set.
• CopyWithZone has been renamed to copy(with: _)

2019-04-15 11:52 UTC, iceman201 approved these changes

2019-04-15 11:53 UTC, iceman201 requested changes

2019-04-15 11:53 UTC, iceman201 commented on ChartsRealm/Classes/Data/RealmBarDataSet.swift
> +    open override func copy(with zone: NSZone? = nil) -> Any {
maybe better to match the code style put the { next line

2019-04-17 01:11 UTC, liuxuan30 commented
could you try to update to Swift 5.0 to align with Charts 3.3? Not sure if Realm has updated though

2019-05-28 06:04 UTC, closed without merging